# Original by David Nickerson.
# Changes:
#	
#----------------------------------------------------------------------------------------------------------------------------------

MAKEFLAGS = --no-builtin-rules --warn-undefined-variables
SHELL = /bin/bash

#----------------------------------------------------------------------------------------------------------------------------------

ifndef OPENCMISSEXTRAS_ROOT
  OPENCMISSEXTRAS_ROOT := ${OPENCMISS_ROOT}/../OpenCMISSExtras
  CDA_ROOT := $(CURDIR)/../../../..
  OCE_GLOBAL_ROOT := $(CURDIR)/../../OpenCMISSExtras
else
  CDA_ROOT := ${OPENCMISSEXTRAS_ROOT}
  OCE_GLOBAL_ROOT := ${OPENCMISSEXTRAS_ROOT}
endif
MAKEINC_ROOT := $(OCE_GLOBAL_ROOT)/utils/make

include $(MAKEINC_ROOT)/Makefile.inc

BUILD_NAME = $(ENVIRONMENT)$(BUILD_TYPE)$(NOMPI_TOOLCHAIN)

LIBOCCELLML_INSTALL_DIR = $(OPENCMISS_ROOT)/cellml/$(BUILD_NAME)
LIBOCCELLML_BUILD_DIR = $(CURDIR)/build/$(BUILD_NAME)


