# Original by David Nickerson.
# Changes:
#	
#----------------------------------------------------------------------------------------------------------------------------------

MAKEFLAGS = --no-builtin-rules --warn-undefined-variables
SHELL = /bin/bash

#----------------------------------------------------------------------------------------------------------------------------------


ifndef OPENCMISS_ROOT
  OPENCMISS_ROOT := ..
  MAKEINC_ROOT := $(CURDIR)/../../../../../opencmiss/cm/utils
else
  MAKEINC_ROOT := ${OPENCMISS_ROOT}/cm/utils
endif

ifndef OPENCMISSEXTRAS_ROOT
  OPENCMISSEXTRAS_ROOT := ${OPENCMISS_ROOT}/../opencmissextras
  CDA_ROOT := $(CURDIR)/../../../..
else
  CDA_ROOT := ${OPENCMISSEXTRAS_ROOT}
endif

include $(MAKEINC_ROOT)/Makefile.inc

BUILD_NAME = $(LIB_ARCH_DIR)$(DEBUG_SUFFIX)$(PROF_SUFFIX)/$(COMPILER)

CDA_DIR = $(CDA_ROOT)/cellml/$(BUILD_NAME)

LIBOCCELLML_INSTALL_DIR = $(OPENCMISS_ROOT)/cellml/$(BUILD_NAME)
LIBOCCELLML_BUILD_DIR = $(CURDIR)/build/$(BUILD_NAME)


