# Original by David Nickerson.
# Changes:
#	
#----------------------------------------------------------------------------------------------------------------------------------

MAKEFLAGS = --no-builtin-rules --warn-undefined-variables
SHELL = /bin/bash

#----------------------------------------------------------------------------------------------------------------------------------

ifndef OPENCMISSEXTRAS_ROOT
  OPENCMISSEXTRAS_ROOT := ${OPENCMISS_ROOT}/../opencmissextras
  CDA_ROOT := $(CURDIR)/../../../..
  MAKEINC_ROOT := $(CURDIR)/../../opencmissextras/utils
else
  CDA_ROOT := ${OPENCMISSEXTRAS_ROOT}
  MAKEINC_ROOT := ${OPENCMISSEXTRAS_ROOT}/utils
endif

include $(MAKEINC_ROOT)/Makefile.inc

ifdef COMPILER_VERSION
  BUILD_NAME = $(LIB_ARCH_DIR)$(DEBUG_SUFFIX)$(PROF_SUFFIX)/$(COMPILER)_$(COMPILER_VERSION)
else
  BUILD_NAME = $(LIB_ARCH_DIR)$(DEBUG_SUFFIX)$(PROF_SUFFIX)/$(COMPILER)
endif

CDA_DIR = $(CDA_ROOT)/cellml/$(BUILD_NAME)

LIBOCCELLML_INSTALL_DIR = $(OPENCMISS_ROOT)/cellml/$(BUILD_NAME)
LIBOCCELLML_BUILD_DIR = $(CURDIR)/build/$(BUILD_NAME)


