#ifndef _CCGS_REQUIRED_FUNCTIONS_H_
#define _CCGS_REQUIRED_FUNCTIONS_H_

#include <stdarg.h>

#ifdef __cplusplus
extern "C"
{
#endif
  /* The functions which may be used by the code generated by the CCGS */
  double factorial(double x);
  double arbitrary_log(double value, double logbase);
  double gcd_pair(double a, double b);
  double lcm_pair(double a, double b);
  double gcd_multi(uint32_t size, ...);
  double lcm_multi(uint32_t size, ...);
  double multi_min(uint32_t size, ...);
  double multi_max(uint32_t size, ...);
  double safe_quotient(double num, double den);
  double safe_remainder(double num, double den);
  double safe_factorof(double num, double den);
  void NR_MINIMISE(double(*func)(double VOI, double *C, double *R, double *S, double *A),
                   double VOI,double *C,double *R,double *S,double *A,double *V);
#ifdef __cplusplus
}
#endif


#endif /* _CCGS_REQUIRED_FUNCTIONS_H_ */
