/* FIXME: this should be generated by CMake */
#ifndef occellml_config_h
#define occellml_config_h

#ifdef HAVE_INTTYPES_H
#	include <inttypes.h>
#else
	/* need to check what these should really be */
	typedef unsigned int uint32_t;
	typedef unsigned short uint16_t;
#endif

/* This is in the CDA config, required? (WIN32 already defined (by cmake?))
#ifdef _MSC_VER
# define WIN32
# undef __STDC__
#endif
*/

#endif // occellml_config_h